name: Deploy preview environment

on:
  push:
    branches:
      - "*"   # toutes les branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "Building Docker image for branch $BRANCH_NAME"
          docker build -t test:$BRANCH_NAME .

      - name: Remove old container if exists
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          if [ "$(docker ps -aq -f name=$BRANCH_NAME)" ]; then
            docker rm -f "$BRANCH_NAME"
          fi

      - name: Run container
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          docker run -d \
            --name "$BRANCH_NAME" \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.$BRANCH_NAME.rule=Host(\"$BRANCH_NAME.dev.monapp.com\")" \
            --label "traefik.http.routers.$BRANCH_NAME.entrypoints=web" \
            test:"$BRANCH_NAME"

      - name: List running containers
        run: docker ps
