name: Manual Workflow

on:
  workflow_dispatch:
    branches:
      - main
      - test
jobs:
  run-manually:
    runs-on: ubuntu-latest
    steps:
      - name: Afficher un message
        run: echo "Workflow lancé manuellement !"
